# Generated by Django 4.2.1 on 2023-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
