# Generated by Django 4.2.1 on 2023-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_proveedor_dni_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
